"""create content actor narrative tables

Revision ID: 8817791c416d
Revises: 
Create Date: 2026-02-25 14:16:39.171804
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8817791c416d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_id', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('profile_url', sa.String(length=2048), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actor_platform_id', 'actors', ['platform', 'platform_id'], unique=True)
    op.create_index('ix_actor_username', 'actors', ['username'], unique=False)
    op.create_table('content_records',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('platform_content_id', sa.String(length=256), nullable=False),
    sa.Column('content_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('parent_id', sa.String(length=256), nullable=True),
    sa.Column('root_id', sa.String(length=256), nullable=True),
    sa.Column('conversation_id', sa.String(length=256), nullable=True),
    sa.Column('actor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engagement', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('geo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nlp', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('narrative_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_created_at', 'content_records', ['content_created_at'], unique=False)
    op.create_index('ix_content_platform', 'content_records', ['platform'], unique=False)
    op.create_index('ix_content_platform_id', 'content_records', ['platform', 'platform_content_id'], unique=True)
    op.create_table('narratives',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('representative_content_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('parent_narrative_id', sa.UUID(), nullable=True),
    sa.Column('related_narrative_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('narratives')
    op.drop_index('ix_content_platform_id', table_name='content_records')
    op.drop_index('ix_content_platform', table_name='content_records')
    op.drop_index('ix_content_created_at', table_name='content_records')
    op.drop_table('content_records')
    op.drop_index('ix_actor_username', table_name='actors')
    op.drop_index('ix_actor_platform_id', table_name='actors')
    op.drop_table('actors')
    # ### end Alembic commands ###
